services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server_resumes
    platform: linux/amd64
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=WeeCompany_2025
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data:
    name: sql-data-resumes